eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

spring:
  cloud:
    discovery:
      enabled: true
    config:
      enabled: true

logging:
  level:
    org.springframework: info
    io.github.resilience4j: debug