server:
  port: 9083

spring:
  cloud:
    gateway:
      routes:
        - id: fraud
          uri: lb://fraud-verifier
          predicates:
            - Path=/fraud-verifier/**
          filters:
            - StripPrefix=1
            - name: Retry
              args:
                retries: 3

management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - prometheus
