services:
  my-eureka-service:
    build: ./eureka-server
    container_name: my-eureka-service
    ports:
      - '8761:8761'
    expose:
      - 8761
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
  my-config-service:
    build: ./config-server
    container_name: my-config-service
    ports:
      - '9888:9888'
    expose:
      - 9888
    environment:
      - DISCOVERY_SERVICE_URL=http://my-eureka-service:8761/eureka
    healthcheck:
      test: [ "CMD","curl","-f","http://localhost:9888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      my-eureka-service:
          condition: service_healthy
    restart: always
  my-card-service:
    build: ./card-service
    container_name: my-card-service
    ports:
      - '9080:9080'
    expose:
      - 9080
    environment:
      - DISCOVERY_SERVICE_URL=http://my-eureka-service:8761/eureka
      - CONFIG_SERVICE=http://my-config-service:9888
    depends_on:
      my-config-service:
          condition: service_healthy
  my-user-service:
    build: ./user-service
    container_name: my-user-service
    ports:
      - '9082:9082'
    expose:
      - 9082
    environment:
      - DISCOVERY_SERVICE_URL=http://my-eureka-service:8761/eureka
      - CONFIG_SERVICE=http://my-config-service:9888
    depends_on:
      my-config-service:
        condition: service_healthy
  my-fraud-verifier:
    build: ./fraud-verifier
    container_name: my-fraud-verifier
    ports:
      - '9086:9086'
    expose:
      - 9086
    environment:
      - DISCOVERY_SERVICE_URL=http://my-eureka-service:8761/eureka
      - CONFIG_SERVICE=http://my-config-service:9888
    depends_on:
      my-config-service:
        condition: service_healthy
  my-gateway-proxy:
    build: ./gateway-proxy
    container_name: my-gateway-proxy
    ports:
      - '9083:9083'
    expose:
      - 9083
    environment:
      - CONFIG_SERVICE=http://my-config-service:9888
      - DISCOVERY_SERVICE_URL=http://my-eureka-service:8761/eureka
    depends_on:
      my-config-service:
        condition: service_healthy