server:
  port: 9888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Hamzagharsellaoui/spring-cloud-demo.git
          search-paths: config-repo/spring-cloud-intro-demo-config/application.properties
          default-label: main